export const placeholders = [
  "What is Googol?",
  "Is Java the best programming language?",
  "How to make a good cup of coffee?",
  "Best places to visit in 2023",
  "Optimizing inverted index structures",
  "Is UI better than ITB?",
  "Elon Musk's net worth",
  "How to get A in Fasilkom?",
  "Evaluating precision and recall in search results",
  "Taylor Swift latest album",
  "Brainstorm names for my fantasy football team",
  "How many subscribers does LalaLeen have?",
  "Real Madrid vs Barcelona",
];
